name: 'Sync Pull Requests to Azure Boards'
description: 'Create a work item in Azure DevOps when a Pull Request is created'
author: 'danhellem'
branding:
  icon: "git-pull-request"
  color: "blue"
inputs:
  ado_token: 
    description: 'Azure DevOps Personal Access Token'
    default: ''
  ado_organization:
    description: 'Organization Name'
    default: ''
  ado_project: 
    description: 'Project Name'
    default: ''
  ado_wit: 
    description: 'Work Item Type (usually a custom work item type)'
    default: 'Pull Request' 
  ado_close_state: 
    description: 'Closed State'
    default: 'Closed' 
  ado_active_state: 
    description: 'In Progress state that the PR will get set too after it is created'
    default: 'Active'
outputs:
  id:
    description: "id of work item created"
runs:
  using: 'node12'
  main: 'dist/index.js'
